version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: avishka
      POSTGRES_PASSWORD: avishka12345
      POSTGRES_DB: mentor
    ports:
      - "6500:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    container_name: mentor_app
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL: postgresql://avishka:avishka12345@localhost:6500/mentor
    depends_on:
      - serviceName: postgres
